### ISSUE TITLE
考虑支持 laravel 4.x 么？

### ISSUE THREAD

**Issue by eggao** [fex-team/laravel-fis#1]
首先非常感谢提供laravel-fis解决方案。
目前项目使用的是4.x，请问考虑支持4.x吗？

**Comment by 2betop** [comment]
暂不支持，多谢关注。

这个只是 laravel 解决方案的一部分，晚点会出更加详细的开发文档和实现思路。（ps：你发现得太快了）

**Comment by 2betop** [comment]
功能说明：https://github.com/fex-team/laravel-fis/blob/master/functions.md

不了解 laravel 4，所以如果要扩展，把类似代码移植过去就行了。
