### ISSUE TITLE
@require的顺序问题

### ISSUE THREAD

**Issue by hylin** [fex-team/laravel-fis#3]
如果在模板A中require('a.css')
B模板继承自A，再引入自己的require('b.css')
编译后b.css输出在a.css的前面
常理来说，扩展的模板引入的资源极有可能是要覆盖父模板的样式的
能调整一下顺序逻辑吗？

**Comment by 2betop** [comment]
跟 block 所在的位置有关，你的 extends  中是在什么 block 里面添加的 css, 然后你在父模板中控制 这个block 的位置。

**Comment by hylin** [comment]
嗯 好了。之前require('b.css')放在section外面，放section里面顺序就对了
