### ISSUE TITLE
extend 文件名问题

### ISSUE THREAD

**Issue by dlutqjy** [fex-team/laravel-fis#5]
我这试了下demo，由于@extends('widget/layout/frame.blade.php') 是这种写法，laravel5 直接报错了， View [.widget.layout.front.blade.php] not found. (View: D:\develop\laravel\resources\views\index.blade.php)

**Comment by 2betop** [comment]
貌似你的文件名错了？

front 还是 frame ?

**Comment by dlutqjy** [comment]
原始日志如下：
View [.widget.layout.front.blade.php] not found. (View: D:\develop\svn\phpsvn\laravel\resources\views\index.blade.php

将index.blade.php文件中的@extends('/widget/layout/front.blade.php') 改为@extends('/widget/layout/front')  就好了。

@widget('../header/header.blade.php')  也有相同的报错， 尝试修改为@widget('../header/header')后，fis3 release后变为 @widget('widget/header/header.js')，故widget单纯修改没能解决该问题。

人工修改fis3 release后的代码中的@extends和@widget， 代码才可以正常运行。
我用的是laravel 5.1.\* , demo代码是兼容laravel版本是？

**Comment by 2betop** [comment]
具体 5.1.几？ 回头我试试看。

**Comment by dlutqjy** [comment]
https://laravel.com/docs/5.1/installation
5.1

**Comment by dlutqjy** [comment]
帮忙试了吗？ @widget 问题  @2betop

**Comment by 2betop** [comment]
亲测 5.1.x 也没问题啊

**Comment by 2betop** [comment]
5.1.40

**Comment by 2betop** [comment]
5.2.31 也没问题

**Comment by dlutqjy** [comment]
多谢， 我也试了下，调试后发现fis和larvel-swagger插件boot函数有冲突。在app.conf配置里，需要把fis配置在laravel-swagger之前。

**Comment by oxUnd** [comment]
冲突是名字一样了么？

**Comment by dlutqjy** [comment]
laravel-swagger在boot函数里会实例化容器里的view， fis会在boot函数里重写view用到的FileViewFinder,  重写FileViewFinder必须在view实例化前，不然重写就无效。 不同插件的boot函数是根据app.conf配置里的顺序执行。

**Comment by ql2005** [comment]
@dlutqjy 出现同样的问题....但是没明白怎么解决 =,=
没有app.conf啊

还是指 config/app.php ?
我把  
`Fis\Providers\ResourceProvider::class,`
放到providers的第一行~ 可以了...
